name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opend,reopend] #必要に応じて適宜削除する。
    branches: [ main ]


jobs: 

  SonarQube_on_windows2019:
  
    runs-on: [self-hosted, windows, x64]
    
    steps:
    - uses: actions/checkout@v2
    - name: SonarQube Scan
      shell: cmd
